In [ ]:
"iwf-competition-analysis-visualizations"
"""Questions:
What is the average body weight for men and women?
What is the average weight of successful Max Snatch, 
    Max C/J, and Total for IWF, Oly, and all for men and women?
What is ratio of missed lifts to completed lifts 
    for Oly, IWF, and all for men and women?
What are the top 10 most popular country codes?
What is the ratio of female to male competitors for Oly, IWF, and all?
Is the number of female competitors increasing? 
Is there a correlation between body weight and 
    max snatch, max c/j, and total for men and women?
    
Comparison of max snatch, max c/j, and totals for 
    weight classes by 5kg increments for men and women. 
    




Need to clean up country codes? Perhaps using regular expressions?"""

In [ ]:
# # A function to concate all of the above .csv files into one file
# file_name = "Olympic-Weightlifting-total-results-1980-2016"
# wf.datatable_cleanup.concat_csv(file_name)

# import os
# from glob import glob
# import pandas as pd
# import webscraping_functions as wf

In [1]:
from datetime import datetime
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
%matplotlib inline

import webscraping_functions as wf

# #plt.show()

[NbConvertApp] Converting notebook webscraping_functions.ipynb to script
[NbConvertApp] Writing 15105 bytes to webscraping_functions.py

In [ ]:
# Setting custom color palette from hex color codes 
"""
Hexcodes and Color Names
"#B38867", # Coffee
"#283655", # Blueberry
"#69983D", # Green Apple
"#D50000", # Guardsman Red
"#A57298", # Boquet
"#FFAA00", # Web Orange/Goldenrod
"#F18D93", # Pink Tulip
"#F0810F", # Tangerine
"#66A5AD", # Ocean
"""

color_names = "coffee, blueberry, green, red, boquet, goldenrod, pink tulip, tangerine, ocean".split(", ")
hexcodes = "#B38867 #283655 #69983D #D50000 #A57298 #FFAA00 #F18D93 #F0810F #66A5AD".split()
colors_codes = list(zip(color_names, hexcodes))
exercise_names = "Deadlift BackSquat OverheadSquat FrontSquat BenchPress ShoulderPress SnatchPress Snatch Clean&Jerk".split()
color_map= dict(zip(exercise_names, colors_codes))

In [ ]:
color_df = pd.DataFrame.from_dict(color_map, orient="index", columns=["Color Name", "Hexcode"])
color_df

In [ ]:
colors = color_df["Hexcode"].tolist()

In [ ]:
palette = sns.set_palette(sns.color_palette(colors))
sns.set_context("paper")

In [78]:
# country_codes = pd.read_csv("country-codes-alpha-2-3.csv")
iso_country_codes = pd.read_csv("country-codes-alpha-3-only.csv")
iso_country_codes.drop("Unnamed: 0", axis=1, inplace=True)
iso_country_codes.head()

  Alpha-3 code        Country
0          ABW          Aruba
1          AFG    Afghanistan
2          AGO         Angola
3          AIA       Anguilla
4          ALA  Åland Islands

In [79]:
ioc_country_codes = pd.read_csv("country-codes-ioc.csv")
ioc_country_codes.drop("Unnamed: 0", axis=1, inplace=True)
ioc_country_codes.head()

  IOC code      Country                             Other codes used
0      AFG  Afghanistan                                          NaN
1      ALB      Albania                                          NaN
2      ALG      Algeria  AGR (1964)AGL (1968 S) from Spanish Argelia
3      AND      Andorra                                          NaN
4      ANG       Angola                                       ANO[5]

In [80]:
df = pd.read_csv("iwf-oly-weightlifting-combined-total-results-1980-2016.csv", encoding='utf-8')
df.head()

,Unnamed: 0,Year,Event,Gender,Comp Rank,Athlete Name,Nationality,Group,Body Weight (kg),Snatch 1 (kg),Snatch 2 (kg),Snatch 3 (kg),Max Snatch,Snatch Rank,C/J 1 (kg),C/J 2 (kg),C/J 3 (kg),Max C/J,C/J Rank,Total
0,0,1996,iwf,W,1.0,Wan Ni,CHN,A,84.40,102.5,-107.5,-110.0,102.5,2,130.0,135.0,137.5,137.5,1,240.0
1,1,1996,iwf,W,2.0,Karoliina Lundahl,FIN,A,83.10,100.0,105.0,107.5,107.5,1,125.0,-127.5,-127.5,125.0,3,232.5
2,2,1996,iwf,W,3.0,Chen Hsiao-lien,TPE,A,100.40,-95.0,-97.5,97.5,97.5,4,130.0,-137.5,-137.5,130.0,2,227.5
3,3,1996,iwf,W,4.0,Sylvie Iskin,FRA,A,96.85,-100.0,100.0,102.5,102.5,2,117.5,-122.5,122.5,122.5,4,225.0
4,4,1996,iwf,W,5.0,Erika TakÃƒÂ¡cs,HUN,A,96.00,97.5,-100.0,-100.0,97.5,4,120.0,-125.0,-125.0,120.0,5,217.5

In [81]:
df.drop(columns =["Unnamed: 0"], inplace = True)
df["Body Weight (kg)"] = wf.ResultsCleanup.string_to_float(df["Body Weight (kg)"].values.tolist())
df["Snatch 1 (kg)"] = wf.ResultsCleanup.string_to_float(df["Snatch 1 (kg)"].values.tolist())
df["Snatch 2 (kg)"] = wf.ResultsCleanup.string_to_float(df["Snatch 2 (kg)"].values.tolist())
df["Snatch 3 (kg)"] = wf.ResultsCleanup.string_to_float(df["Snatch 3 (kg)"].values.tolist())
df["C/J 1 (kg)"] = wf.ResultsCleanup.string_to_float(df["C/J 1 (kg)"].values.tolist())
df["C/J 2 (kg)"] = wf.ResultsCleanup.string_to_float(df["C/J 2 (kg)"].values.tolist())
df["C/J 3 (kg)"] = wf.ResultsCleanup.string_to_float(df["C/J 3 (kg)"].values.tolist())
df["Max Snatch"] = wf.ResultsCleanup.string_to_float(df["Max Snatch"].values.tolist())
df["Max C/J"] = wf.ResultsCleanup.string_to_float(df["Max C/J"].values.tolist())
df["Total"] = wf.ResultsCleanup.string_to_float(df["Total"].values.tolist())
df["Nationality"] = df["Nationality"].str.strip(")")
# wf.CheckFunctions.change_nation_code(df)
df.fillna(0, inplace=True)
df.head()

,Year,Event,Gender,Comp Rank,Athlete Name,Nationality,Group,Body Weight (kg),Snatch 1 (kg),Snatch 2 (kg),Snatch 3 (kg),Max Snatch,Snatch Rank,C/J 1 (kg),C/J 2 (kg),C/J 3 (kg),Max C/J,C/J Rank,Total
0,1996,iwf,W,1.0,Wan Ni,CHN,A,84.40,102.5,-107.5,-110.0,102.5,2,130.0,135.0,137.5,137.5,1,240.0
1,1996,iwf,W,2.0,Karoliina Lundahl,FIN,A,83.10,100.0,105.0,107.5,107.5,1,125.0,-127.5,-127.5,125.0,3,232.5
2,1996,iwf,W,3.0,Chen Hsiao-lien,TPE,A,100.40,-95.0,-97.5,97.5,97.5,4,130.0,-137.5,-137.5,130.0,2,227.5
3,1996,iwf,W,4.0,Sylvie Iskin,FRA,A,96.85,-100.0,100.0,102.5,102.5,2,117.5,-122.5,122.5,122.5,4,225.0
4,1996,iwf,W,5.0,Erika TakÃƒÂ¡cs,HUN,A,96.00,97.5,-100.0,-100.0,97.5,4,120.0,-125.0,-125.0,120.0,5,217.5

In [92]:
df[::-1].head()

,Year,Event,Gender,Comp Rank,Athlete Name,Nationality,Group,Body Weight (kg),Snatch 1 (kg),Snatch 2 (kg),Snatch 3 (kg),Max Snatch,Snatch Rank,C/J 1 (kg),C/J 2 (kg),C/J 3 (kg),Max C/J,C/J Rank,Total
10198,2016,oly,W,0.0,Jaqueline Ferreira,BRA,A,74.89,-103.0,-103.0,-103.0,-103.0,15,0.0,0.0,0.0,0.0,15,0.0
10197,2016,oly,W,14.0,Samira Ouass,MAR,B,73.68,70.0,75.0,-80.0,75.0,14,90.0,-96.0,97.0,97.0,14,172.0
10196,2016,oly,W,13.0,Assiya Ã„Â°pek,TUR,B,69.77,80.0,83.0,-85.0,83.0,13,95.0,100.0,103.0,103.0,13,186.0
10195,2016,oly,W,12.0,Natalia PriÃˆâ„¢cepa,MDA,B,73.72,93.0,97.0,-100.0,97.0,11,110.0,116.0,-123.0,116.0,12,213.0
10194,2016,oly,W,11.0,Mary Opeloge,WSM,B,74.56,97.0,100.0,-102.0,100.0,9,115.0,117.0,118.0,118.0,11,218.0

In [83]:
"""Working copy. Need to find non Alpha 3 code countries. """
# iso_code_list = []

for country in df["Nationality"].values.tolist():
    if country in iso_country_codes["Country"].values.tolist():
        iso_dataframe_index = df["Nationality"].values.tolist().index(country)
        iso_code_index = iso_country_codes["Country"].values.tolist().index(country)
        iso_code = iso_country_codes["Alpha-3 code"][iso_code_index]
#         iso_code_list.append(code)
        df["Nationality"][iso_dataframe_index] = iso_code
    elif country in ioc_country_codes["Country"].values.tolist():
        ioc_dataframe_index = df["Nationality"].values.tolist().index(country)
        ioc_code_index = ioc_country_codes["Country"].values.tolist().index(country)
        ioc_code = ioc_country_codes["IOC code"][ioc_code_index]
        df["Nationality"][ioc_dataframe_index] = ioc_code
        
#         df["Nationality"][index] = code_list[index]
#     else:
#         index = df["Nationality"].values.tolist().index(country)
#         code = df["Nationality"].values.tolist()[index]
#         code_list.append(code)
#         df["Nationality"][index] = code_list[index]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [84]:
df["Nationality"][::-1].head()

10198    BRA
10197    MAR
10196    TUR
10195    MDA
10194    WSM
Name: Nationality, dtype: object

In [86]:
ioc_country_codes["Country"].values.tolist()

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'American Samoa',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bangladesh',
 'Barbados',
 'Burundi',
 'Belgium',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bosnia and Herzegovina',
 'Belize',
 'Belarus',
 'Bolivia',
 'Botswana',
 'Brazil',
 'Bahrain',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Central African Republic',
 'Cambodia',
 'Canada',
 'Cayman Islands',
 'Republic of the Congo',
 'Chad',
 'Chile',
 'China',
 'Ivory Coast',
 'Cameroon',
 'Democratic Republic of the Congo',
 'Cook Islands',
 'Colombia',
 'Comoros',
 'Cape Verde',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'Eritrea',
 'El Salvador',
 'Spain',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Federated States of Micronesia',
 'Gabon',
 'The Gambia',
 'Great Britain',
 'Guinea-Bissau',
 'Georgia',
 'Equatorial Guinea',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guam',
 'Guyana',
 'Haiti',
 'Hong Kong, China',
 'Honduras',
 'Hungary',
 'Indonesia',
 'India',
 'Iran',
 'Ireland',
 'Iraq',
 'Iceland',
 'Israel',
 'Virgin Islands',
 'Italy',
 'British Virgin Islands',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyzstan',
 'Kiribati',
 'South Korea',
 'Kosovo',
 'Saudi Arabia',
 'Kuwait',
 'Laos',
 'Latvia',
 'Libya',
 'Lebanon',
 'Liberia',
 'Saint Lucia',
 'Lesotho',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Morocco',
 'Malaysia',
 'Malawi',
 'Moldova',
 'Maldives',
 'Mexico',
 'Mongolia',
 'Marshall Islands',
 ' North Macedonia',
 'Mali',
 'Malta',
 'Montenegro',
 'Monaco',
 'Mozambique',
 'Mauritius',
 'Mauritania',
 'Myanmar',
 'Namibia',
 'Nicaragua',
 'Netherlands',
 'Nepal',
 'Nigeria',
 'Niger',
 'Norway',
 'Nauru',
 'New Zealand',
 'Oman',
 'Pakistan',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Palestine',
 'Palau',
 'Papua New Guinea',
 'Poland',
 'Portugal',
 'North Korea',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'South Africa',
 'Russia',
 'Rwanda',
 'Samoa',
 'Senegal',
 'Seychelles',
 'Singapore',
 'Saint Kitts and Nevis',
 'Sierra Leone',
 'Slovenia',
 'San Marino',
 'Solomon Islands',
 'Somalia',
 'Serbia',
 'Sri Lanka',
 'South Sudan',
 'São Tomé and Príncipe',
 'Sudan',
 'Switzerland',
 'Suriname',
 'Slovakia',
 'Sweden',
 'Swaziland',
 'Syria',
 'Tanzania',
 'Tonga',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'East Timor',
 'Togo',
 'Chinese Taipei',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Tuvalu',
 'United Arab Emirates',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'United States',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Saint Vincent and the Grenadines',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [91]:
for country in df["Nationality"].values.tolist():
    if len(country) != 3:
        print(f"{country}")

In [61]:
"""Working copy. Need to find non Alpha 3 code countries. """
for country in df["Nationality"].values.tolist():
    if country in iso_country_codes["Country"].values.tolist():
        iso_dataframe_index = df["Nationality"].values.tolist().index(country)
        iso_code_index = iso_country_codes["Country"].values.tolist().index(country)
        iso_code = iso_country_codes["Alpha-3 code"][iso_code_index]
        df["Nationality"][iso_dataframe_index] = iso_code
    elif country in ioc_country_codes["Country"].values.tolist():
        ioc_dataframe_index = df["Nationality"].values.tolist().index(country)
        ioc_code_index = ioc_country_codes["Country"].values.tolist().index(country)
        ioc_code = ioc_country_codes["IOC code"][ioc_code_index]
        df["Nationality"][ioc_dataframe_index] = ioc_code

In [70]:
df[::-1].head()

,Year,Event,Gender,Comp Rank,Athlete Name,Nationality,Group,Body Weight (kg),Snatch 1 (kg),Snatch 2 (kg),Snatch 3 (kg),Max Snatch,Snatch Rank,C/J 1 (kg),C/J 2 (kg),C/J 3 (kg),Max C/J,C/J Rank,Total
10198,2016,oly,W,0.0,Jaqueline Ferreira,BRA,A,74.89,-103.0,-103.0,-103.0,-103.0,15,0.0,0.0,0.0,0.0,15,0.0
10197,2016,oly,W,14.0,Samira Ouass,MAR,B,73.68,70.0,75.0,-80.0,75.0,14,90.0,-96.0,97.0,97.0,14,172.0
10196,2016,oly,W,13.0,Assiya Ã„Â°pek,TUR,B,69.77,80.0,83.0,-85.0,83.0,13,95.0,100.0,103.0,103.0,13,186.0
10195,2016,oly,W,12.0,Natalia PriÃˆâ„¢cepa,Moldova,B,73.72,93.0,97.0,-100.0,97.0,11,110.0,116.0,-123.0,116.0,12,213.0
10194,2016,oly,W,11.0,Mary Opeloge,WSM,B,74.56,97.0,100.0,-102.0,100.0,9,115.0,117.0,118.0,118.0,11,218.0

In [61]:
"""Working copy. Need to find non Alpha 3 code countries. """
for country in df["Nationality"].values.tolist():
    if country in iso_country_codes["Country"].values.tolist():
        iso_dataframe_index = df["Nationality"].values.tolist().index(country)
        iso_code_index = iso_country_codes["Country"].values.tolist().index(country)
        iso_code = iso_country_codes["Alpha-3 code"][iso_code_index]
        df["Nationality"][iso_dataframe_index] = iso_code
    elif country in ioc_country_codes["Country"].values.tolist():
        ioc_dataframe_index = df["Nationality"].values.tolist().index(country)
        ioc_code_index = ioc_country_codes["Country"].values.tolist().index(country)
        ioc_code = ioc_country_codes["IOC code"][ioc_code_index]
        df["Nationality"][ioc_dataframe_index] = ioc_code

In [69]:
df[::-1].head()

,Year,Event,Gender,Comp Rank,Athlete Name,Nationality,Group,Body Weight (kg),Snatch 1 (kg),Snatch 2 (kg),Snatch 3 (kg),Max Snatch,Snatch Rank,C/J 1 (kg),C/J 2 (kg),C/J 3 (kg),Max C/J,C/J Rank,Total
10198,2016,oly,W,0.0,Jaqueline Ferreira,BRA,A,74.89,-103.0,-103.0,-103.0,-103.0,15,0.0,0.0,0.0,0.0,15,0.0
10197,2016,oly,W,14.0,Samira Ouass,MAR,B,73.68,70.0,75.0,-80.0,75.0,14,90.0,-96.0,97.0,97.0,14,172.0
10196,2016,oly,W,13.0,Assiya Ã„Â°pek,TUR,B,69.77,80.0,83.0,-85.0,83.0,13,95.0,100.0,103.0,103.0,13,186.0
10195,2016,oly,W,12.0,Natalia PriÃˆâ„¢cepa,Moldova,B,73.72,93.0,97.0,-100.0,97.0,11,110.0,116.0,-123.0,116.0,12,213.0
10194,2016,oly,W,11.0,Mary Opeloge,WSM,B,74.56,97.0,100.0,-102.0,100.0,9,115.0,117.0,118.0,118.0,11,218.0

In [7]:
"""Working copy. Need to find non Alpha 3 code countries. """
code_list = []

for country in df["Nationality"].values.tolist():
    if country in country_codes["Country"].values.tolist():
        dataframe_index = df["Nationality"].values.tolist().index(country)
        code_index = country_codes["Country"].values.tolist().index(country)
        code = country_codes["Alpha-3 code"][code_index]
        code_list.append(code)
        df["Nationality"][dataframe_index] = code
        
#         df["Nationality"][index] = code_list[index]
#     else:
#         index = df["Nationality"].values.tolist().index(country)
#         code = df["Nationality"].values.tolist()[index]
#         code_list.append(code)
#         df["Nationality"][index] = code_list[index]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [47]:
for country in df["Nationality"].values.tolist():
    if not country in iso_country_codes["Alpha-3 code"].values.tolist() and not country in iso_country_codes["Country"].values.tolist():
        if not country in ioc_country_codes["IOC code"].values.tolist() and not country in ioc_country_codes["Country"].values.tolist():
            print(f"{country}")

IRE
WAL
WAL
WAL
URS
GDR
TCH
TCH
URS
TCH
URS
GDR
GDR
TCH
URS
TCH
URS
URS
GDR
URS
TCH
GDR
GDR
TCH
URS
YUG
GDR
LIB
URS
TCH
GDR
YUG
ROM
GDR
TCH
TCH
URS
LIB
FRG
URS
FRG
FRG
TCH
TCH
LIB
URS
GDR
URS
LIB
EUN
EUN
TCH
EUN
EUN
TCH
TCH
EUN
TCH
EUN
EUN
TCH
EUN
EUN
EUN
LIB
YUG
IOA
North Korea
Vietnam
Chinese Taipei
Vietnam
South Korea
Venezuela
North Korea
United States
South Korea
South Korea
Venezuela
Venezuela
United States
Chinese Taipei
Vietnam
Chinese Taipei
South Korea
Chinese Taipei
Venezuela
North Korea
Great Britain
North Korea
United States
Moldova

In [27]:
for country in df["Nationality"].values.tolist():
    if not country in country_codes["Alpha-3 code"].values.tolist() and not country in country_codes["Country"].values.tolist():
        print(f"{country}")

TPE
GRE
TPE
BUL
TPE
BUL
GRE
BUL
TPE
BUL
GRE
GRE
BUL
TPE
BUL
GRE
TPE
TPE
GRE
BUL
TPE
GRE
GRE
GRE
TPE
GER
GER
LAT
LAT
TPE
GER
LAT
TPE
BUL
TPE
BUL
BUL
TPE
TPE
BUL
MAS
MAS
BUL
DEN
NED
SUI
TPE
ALG
BUL
BUL
GER
TPE
URU
LAT
TPE
NED
GER
LAT
GER
CHI
TPE
TPE
TPE
MYA
NGR
GRE
TPE
INA
MYA
TPE
INA
BUL
TPE
MYA
GRE
BUL
MYA
NED
TPE
INA
MYA
TPE
TPE
GRE
MYA
TPE
MYA
GRE
GRE
TPE
MYA
NGR
MYA
GER
GRE
LAT
GRE
GER
TPE
ALG
NED
GER
LAT
GER
CRO
BUL
ALG
GRE
CRO
BUL
BUL
TPE
POR
IRE
BUL
GRE
BUL
GRE
ALG
LAT
NED
DEN
BUL
BUL
GRE
GER
GER
TPE
SUI
CRO
GRE
GER
BUL
CRO
CRO
LAT
LAT
GRE
GER
GRE
GER
LAT
DEN
TPE
CRO
NED
TPE
GER
DEN
TPE
TPE
BUL
BUL
GRE
TPE
BUL
GRE
NED
TPE
GER
TPE
BUL
GER
GRE
DEN
GRE
GRE
TPE
IRI
LAT
GER
LAT
PUR
ALG
NED
DEN
NED
GER
DEN
IRI
GER
LAT
CHI
TPE
DEN
NGR
NED
GER
TPE
BUL
TPE
GUA
ALG
LAT
ESA
RSA
NGR
GRE
BUL
CRO
KSA
IRI
GUA
GUA
BUL
BUL
GRE
GRE
IRI
INA
DEN
ALG
IRI
ALG
TPE
RSA
NED
GRE
BUL
BUL
GER
NGR
LAT
NED
GUA
TPE
POR
SAM
POR
SUI
IRI
NED
IRI
GRE
GER
GRE
BUL
GER
LAT
LAT
SAM
CRO
TPE
SUI
SUI
GUA
URU
DEN
DEN
NED
GRE
GRE
BUL
IRI
GER
LAT
TPE
DEN
DEN
SUI
SUI
LBA
POR
NGR
NGR
DEN
TPE
BUL
INA
MYA
INA
TPE
MYA
POR
NED
TPE
INA
INA
MYA
NGR
BUL
BUL
GRE
DEN
POR
POR
TPE
BUL
MYA
NGR
MGL
ESA
GRE
POR
DEN
DEN
NED
ALG
NED
TPE
GRE
NGR
BUL
GER
FIJ
NED
DEN
ALG
DEN
PUR
BUL
BUL
GRE
NGR
ESA
PUR
DEN
NED
TPE
GRE
NGR
TPE
MYA
GER
GRE
GER
GRE
MRI
GER
CHI
BUL
BUL
GER
GRE
GER
SUI
CRO
IRI
TPE
BUL
CRO
BUL
GRE
NGR
ALG
IRI
BUL
BUL
GRE
GRE
SUI
IRI
GER
BUL
IRI
BUL
GRE
GER
TPE
NGR
GRE
GRE
NGR
TPE
TPE
NGR
BUL
MGL
DEN
GRE
TPE
BUL
ALG
TPE
GRE
NED
TPE
NGR
GRE
GRE
IRI
BUL
GER
CHI
BUL
IRI
GER
GER
CRO
TPE
TPE
GRE
BUL
GRE
CRO
GRE
TPE
LAT
IRI
IRI
BUL
BUL
IRI
IRI
BUL
LAT
BUL
IRI
LAT
GRE
GRE
BUL
GER
GRE
NED
LAT
IRI
GRE
GER
GRE
BUL
TPE
BUL
TPE
TPE
GRE
BUL
TPE
ALG
DEN
GRE
BUL
BUL
ALG
GRE
LAT
IRI
BUL
LAT
BUL
ALG
GER
GER
GER
IRI
GER
SUI
BUL
TPE
INA
TPE
KSA
ALG
INA
GRE
ESA
INA
KSA
TPE
KSA
ESA
TPE
INA
CRO
INA
IRI
KSA
KSA
IRI
BUL
GER
GER
ALG
TPE
IRI
IRI
KSA
BUL
PUR
SUI
BUL
BUL
IRI
GER
KSA
NED
GER
KSA
PUR
GRE
BUL
GRE
NGR
BUL
INA
TPE
GRE
TPE
NGR
ESA
INA
NGR
INA
INA
INA
NGR
GRE
PUR
TPE
BUL
BUL
ALG
NGR
TPE
PUR
BUL
TPE
ESA
BUL
TPE
BUL
NGR
TPE
GER
NGR
IRI
LAT
GRE
GER
GER
GRE
TPE
VIE
TPE
IRI
MAS
BUL
TPE
MAD
BAN
BUL
BUL
GER
BUL
GRE
RSA
SAM
PLE
BUL
IRI
GRE
GER
IRI
BAN
GRE
NED
GRE
TPE
BUL
RSA
BAN
TPE
WAL
BAN
GRE
BAN
BUL
PUR
GRE
BUL
ALG
TPE
BUL
IRI
LAT
GRE
GER
CHI
CRO
BUL
BUL
GER
GRE
SUI
TPE
CHI
GER
VIE
TPE
INA
INA
ESA
INA
GRE
TPE
BUL
CRO
CHI
BUL
BUL
TPE
GER
PUR
TPE
CRO
GER
GRE
BUL
GRE
CRO
TPE
CHI
BUL
CRO
RSA
CHI
CHI
GER
GRE
GER
GRE
GER
PUR
CHI
TPE
BUL
ESA
GRE
BUL
GRE
TPE
TPE
CHI
NED
VIE
TPE
PUR
BUL
BUL
INA
TPE
INA
TPE
GRE
GRE
PUR
TPE
ESA
BUL
TPE
VIE
BUL
GRE
CHI
BUL
BUL
WAL
INA
GER
VIE
GRE
LAT
BUL
GRE
IRI
IRI
GER
TPE
TPE
INA
RSA
BAN
VIE
BUL
GRE
GER
IRI
IRI
TPE
LAT
SAM
INA
VIE
BAN
GRE
INA
GRE
ESA
TPE
VIE
MAS
BUL
INA
BUL
VIE
TPE
MAS
NGR
HON
NEP
MAS
SRI
BUL
BUL
MAS
GRE
TPE
TPE
INA
GER
NGR
GER
LAT
VIE
RSA
MAS
BUL
GER
INA
IRI
IRI
NGR
MAS
HON
MON
GRE
VIE
BUL
GRE
GER
LAT
IRI
LAT
IRI
INA
RSA
GRE
GER
TPE
INA
VIE
GER
GRE
GRE
NGR
SAM
BUL
ESA
BUL
TPE
TGA
VIE
INA
VIE
TPE
BUL
MYA
TPE
RSA
NGR
INA
VIE
TPE
GRE
GER
MYA
GRE
NGR
TPE
TPE
GRE
SOL
VIE
MYA
GRE
VIE
BUL
NGR
INA
LAT
NEP
NED
INA
MYA
VIE
GRE
TPE
BUL
INA
BUL
NGR
MYA
VIE
GER
BUL
RSA
INA
MYA
GER
TPE
LAT
PLE
INA
TPE
INA
TPE
IRI
INA
SRI
WAL
CRO
PLE
GER
PLE
MRI
UAE
IRI
TPE
LAT
PLE
SAM
NGR
GER
NGR
TPE
TPE
NGR
TPE
TPE
TPE
GER
INA
IRI
GER
IRI
GRE
TPE
GUA
TPE
RSA
LAT
GER
IRI
IRI
LAT
GER
LAT
GRE
TPE
TPE
INA
INA
ESA
ESA
FIJ
KSA
KSA
VIE
INA
INA
GRE
RSA
KSA
INA
TPE
RSA
IRI
INA
KSA
IRI
GER
INA
SUI
RSA
KSA
KSA
KOS
GER
GRE
URU
KSA
MRI
CRO
IRI
GRE
GER
GRE
TPE
RSA
PUR
KSA
GER
TPE
MGL
MGL
TPE
RSA
GRE
INA
INA
TPE
GER
TPE
DEN
GRE
UAE
PUR
MGL
INA
GER
UAE
UAE
TPE
MGL
GRE
MGL
PUR
MGL
INA
VIE
INA
GER
TPE
PUR
TPE
GER
PUR
MGL
IRI
IRI
GER
TPE
GUA
CRO
LAT
CRC
IRI
IRI
LAT
GER
TPE
SAM
CHI
VIE
TPE
PHI
ESA
FIJ
ESA
TPE
VIE
INA
INA
INA
MAS
GRE
ASA
IRI
MAS
INA
INA
GER
GUA
GER
NGR
INA
GRE
TPE
SUI
IRI
GER
SUI
CRO
IRI
IRI
GRE
GRE
NGR
PUR
SAM
NGR
GER
TPE
SAM
PUR
INA
ESA
TPE
NGR
GER
INA
INA
GRE
DEN
MAS
PHI
TPE
GER
GER
NGR
FIJ
SOL
MGL
NGR
VIE
GRE
MGL
TPE
TPE
INA
SEY
GER
SOL
NGR
SAM
GER
GER
NGR
IRI
GUA
IRI
LAT
IRI
GRE
CRO
VIE
VIE
BUL
BUL
IRI
IRI
IRI
GER
SEY
IRI
GER
BUL
BUL
GER
VIE
NED
CRO
GER
GRE
IRI
MAS
GUA
VIE
PUR
MAS
TPE
SEY
BUL
MGL
IRI
GER
TPE
CRO
GER
IRI
LAT
IRI
GER
GER
TPE
ALG
VIE
VIE
TPE
KSA
IRI
INA
MAS
TPE
BUL
CHI
KSA
ALG
INA
INA
BUL
KSA
KSA
TPE
ALG
GRE
MGL
BUL
INA
IRI
INA
TPE
GER
MAS
KSA
TPE
IRI
KSA
BUL
INA
GER
GER
VIE
GRE
ALG
DEN
IRI
BUL
GRE
GER
GRE
IRI
LBA
KSA
VIE
CRO
ALG
INA
BUL
ALG
GRE
KSA
VIE
INA
MRI
GER
INA
PUR
TPE
BUL
GER
INA
LAT
MGL
MGL
TPE
TPE
GRE
MRI
GRE
CRO
UAE
TPE
GER
CRO
BUL
MGL
INA
MGL
NED
TPE
CHI
GER
GER
CHI
TPE
GER
GER
IRI
CRO
LAT
GER
GER
BUL
IRI
VIE
PHI
INA
INA
VIE
TPE
FIJ
MGL
CHI
KSA
INA
INA
VIE
KSA
TPE
IRI
SRI
TPE
MGL
BUL
KSA
BUL
ESA
INA
INA
TPE
GER
GER
KSA
KSA
MGL
IRI
SRI
KOS
GER
GER
INA
VIE
CHI
DEN
SRI
MGL
MGL
IRI
BUL
IRI
VIE
INA
CRO
SUI
IRI
TPE
ASA
DEN
NGR
MRI
GRE
VIE
TPE
INA
MRI
GER
PUR
VIE
TPE
PHI
LAT
INA
INA
MGL
NCA
MGL
DEN
URU
TPE
TPE
SOL
DEN
MGL
TPE
NGR
INA
RSA
SEY
NCA
MGL
ARU
MGL
GER
INA
FIJ
DEN
TPE
CHI
TPE
MGL
CRC
MGL
IRI
IRI
ALG
GER
IRI
LAT
BUL
IRI
TPE
DEN
VIE
VIE
KSA
FIJ
MAS
TPE
BUL
VIE
KSA
VIE
KSA
GER
KSA
KSA
GER
GER
GER
DEN
TPE
VIE
CHI
IRI
GER
CRO
KSA
VIE
IRI
GER
IRI
IRI
BUL
TPE
GER
VIE
VIE
BUL
PHI
MRI
DEN
VIE
VIE
TPE
TPE
LAT
TPE
RSA
BUL
MGL
VIE
TPE
VIE
FIJ
PHI
TPE
MGL
CHI
TPE
TPE
MGL
IRI
TPE
ALG
GER
IRI
IRI
SAM
SAM
RSA
IRI
BUL
LAT
BUL
GER
TGA
DEN
SAM
BUL
VIE
INA
VIE
PHI
INA
TPE
GER
CHI
TPE
INA
GER
BUL
PHI
KSA
ALG
BUL
INA
KSA
IRI
INA
TPE
GER
DEN
PUR
RSA
GER
LAT
GER
BUL
CHI
TPE
DEN
RSA
KOS
UAE
CRO
BUL
CHI
IRI
SAM
PUR
IRI
IRI
TPE
LAT
GER
GRE
PUR
DEN
PUR
INA
SAM
TPE
TGA
VIE
BUL
INA
VIE
MRI
TPE
INA
PUR
NGR
GRE
PHI
MGL
PHI
NGR
INA
RSA
DEN
URU
DEN
KOS
TPE
LAT
VIE
NGR
INA
GER
DEN
PUR
SLO
PUR
GER
MGL
NGR
RSA
BAN
RSA
TPE
TPE
PHI
GRE
MGL
SUI
DEN
GER
NGR
SUI
TPE
MGL
VIN
CHI
PUR
DEN
ALG
TPE
IRI
NED
GUA
IRI
IRI
IRI
DEN
RSA
BOT
IRI
LAT
TGA
BUL
KSA
VIE
PHI
IRI
INA
SRI
VIE
INA
VIE
MAS
TPE
GER
KSA
TPE
SRI
MAD
SRI
INA
GER
GUA
KSA
MAD
SAM
PHI
TPE
TPE
MAS
BUL
LBA
MGL
BUL
GER
INA
INA
PUR
DEN
SRI
SRI
KSA
PHI
MAS
BUL
GER
LAT
CHI
TPE
SRI
PUR
RSA
IRI
IRI
LBA
CRO
CHI
CRO
URU
DEN
MAS
IRI
LAT
GER
TPE
SAM
ALG
PUR
PUR
IRI
INA
SAM
SAM
TGA
INA
VIE
VIE
PHI
MAD
CHI
BUL
CRO
BAN
NCA
INA
TPE
MRI
PHI
TPE
PUR
SRI
PHI
TPE
DEN
SRI
DEN
SOL
IRI
MGL
CRO
BUL
TPE
LAT
VIE
RSA
DEN
SOL
PHI
MAS
SUI
CRO
BOT
PHI
TPE
GER
GER
VIE
RSA
MGL
DEN
MAD
BAN
URU
CRO
PHI
IRI
DEN
DEN
IRI
TPE
SUI
MAS
MGL
CHI
UAE
VIN
CHI
DEN
MGL
PUR
IRI
TPE
URS
GDR
TCH
TCH
URS
TCH
URS
GDR
GDR
TCH
ALG
ZIM
BUL
LBA
SUI
URS
BUL
GRE
TCH
URS
MGL
GRE
POR
LBA
MGL
URS
GDR
GRE
ALG
LBA
NEP
URS
BUL
TCH
ALG
NGR
NEP
BUL
GDR
BUL
GDR
TCH
GRE
BUL
URS
BUL
YUG
MGL
NGR
GDR
LIB
URS
BUL
TCH
BUL
GDR
YUG
DEN
ROM
BUL
GDR
TCH
TCH
GRE
GUA
URS
MYA
INA
TPE
POR
TPE
SRI
POR
LIB
GRE
TPE
NEP
GUA
INA
ALG
TPE
INA
NGR
NCA
ALG
NGR
NEP
SOL
GUA
FRG
GRE
GRE
PUR
POR
GRE
URS
FRG
FRG
TCH
GRE
NGR
TCH
GRE
BUL
TPE
INA
PHI
LIB
NEP
TPE
URS
INA
ALG
PHI
TPE
INA
TPE
BUL
BUL
GRE
PUR
INA
GDR
URS
GRE
NGR
POR
SAM
LIB
TPE
BUL
EUN
EUN
GER
BUL
TCH
GER
LAT
LBA
NGR
EUN
EUN
BUL
GER
TCH
TCH
IRI
DEN
SAM
KUW
GRE
GER
EUN
BUL
GER
GRE
TCH
IRI
BUL
NCA
SRI
BUL
INA
INA
TPE
MGL
NCA
BUL
BUL
GRE
SAM
GER
INA
ALG
HON
MAD
EUN
BUL
GER
ALG
IRI
EUN
GER
LAT
GER
IRI
INA
GRE
DEN
GUA
SOL
TGA
SUD
MGL
GRE
BUL
GER
TCH
IRI
URU
RSA
PUR
EUN
EUN
EUN
BUL
ASA
LIB
GER
GER
GRE
LAT
NEP
GER
LAT
GER
MRI
GRE
BUL
BUL
TPE
INA
LAT
GUA
MRI
GRE
BUL
PUR
POR
KSA
GRE
GRE
BUL
BUL
TPE
ALG
ALG
ESA
YUG
SOL
BUL
ALG
BUL
GER
GRE
NGR
BUL
GRE
GER
GER
SAM
URU
ARU
GRE
GER
BUL
TPE
LAT
TPE
FIJ
SEY
GRE
GER
BUL
ASA
TGA
GRE
GER
LAT
CHI
KUW
IRI
GER
LAT
ASA
LAT
IRI
BUL
TGA
TPE
TPE
GUA
NCA
MRI
IOA
BUL
CRO
GRE
IRI
NGR
BUL
BUL
BUL
GRE
GRE
GER
PUR
IRI
GRE
GER
GRE
SAM
IRI
GRE
IRI
GER
LAT
NGR
GER
INA
INA
MYA
BUL
BUL
TPE
INA
NGR
MYA
MYA
SEY
ALG
NGR
GRE
FIJ
BUL
BUL
GRE
ESA
PUR
NGR
TPE
IRI
LAT
BUL
GUA
GER
GER
ASA
IRI
INA
ALG
MAS
TPE
TPE
INA
INA
TPE
BUL
GRE
CRO
TPE
KSA
KSA
IRI
GRE
IRI
BUL
GER
LBA
GER
SAM
GRE
GRE
SEY
LBA
BUL
IRI
GRE
IRI
ARU
BUL
GRE
KSA
KSA
GRE
FIJ
BUL
TPE
NGR
TPE
INA
MYA
INA
INA
NGR
BUL
GRE
MGL
VIE
ALG
GRE
BUL
BUL
GRE
ESA
MRI
TPE
GER
LAT
IRI
GER
TGA
GRE
IRI
GUA
VIE
INA
TPE
TPE
MAS
INA
TPE
INA
GER
SRI
NEP
INA
NGR
RSA
FIJ
MON
NGR
SEY
IRI
GER
GRE
GRE
MRI
SAM
NGR
GRE
ESA
TPE
NCA
INA
GER
PUR
PHI
SOL
TPE
VIE
MGL
ALG
CHI
IRI
IRI
GER
TPE
GUA
ARU
GER
IRI
LAT
GER
CHI
ALG
VIE
INA
FIJ
INA
INA
ESA
INA
INA
NGR
SAM
IRI
BUL
IRI
IRI
GRE
KSA
HON
RSA
SAM
GUA
NGR
PUR
MAD
TPE
INA
VIE
GER
TPE
GER
SOL
PHI
BUL
FIJ
NCA
TPE
CHI
UAE
GER
ALG
GER
IRI
TPE
IRI
LAT
GER
North Korea
Vietnam
Chinese Taipei
Vietnam
South Korea
Venezuela
INA
MAS
KSA
TPE
INA
GER
INA
IRI
GRE
CRO
VIE
IRI
IRI
HON
ASA
North Korea
United States
South Korea
South Korea
Venezuela
Venezuela
United States
Chinese Taipei
Vietnam
Chinese Taipei
South Korea
Chinese Taipei
Venezuela
North Korea
Great Britain
North Korea
United States
Moldova

In [ ]:
df["Nationality"].head()

In [ ]:
"""Three attempts:
dataframe index code
dataframe values to list index equals code
append to list, set new column to dataframe."""

code_list = []

for country in df["Nationality"].values.tolist():
    if country in country_codes["Country"].values.tolist():
        index = country_codes["Country"].values.tolist().index(country)
        code = country_codes["Alpha-3 code"][index]
        df["Nationality"][index] = code
    elif country not in country_codes["Alpha-3 code"].values.tolist():
        code_list.append(country)

In [ ]:
"""Three attempts:
dataframe index code
dataframe values to list index equals code
append to list, set new column to dataframe."""

code_list = []

for country in df["Nationality"].values.tolist():
    if country in country_codes["Country"].values.tolist():
        index = country_codes["Country"].values.tolist().index(country)
        code = country_codes["Alpha-3 code"][index]
        df["Nationality"][index] = code
#         code_list.append(code)
#         df["Nationality"][index] = code_list[index]
    else:
        index = df["Nationality"].values.tolist().index(country)
        code = df["Nationality"].values.tolist()[index]
#         code_list.append(code)
#         df["Nationality"][index] = code_list[index]

In [ ]:
df["Nationality"][::-1].values.tolist()

In [ ]:
code_list = []

for country in df["Nationality"].values.tolist():
    if country in country_codes["Country"].values.tolist():
        index = country_codes["Country"].values.tolist().index(country)
        code = country_codes["Alpha-3 code"][index]
        code_list.append(code)
        df["Nationality"][index] = code_list[index]
    else:
        index = df["Nationality"].values.tolist().index(country)
        code = df["Nationality"].values.tolist()[index]
        code_list.append(code)
        df["Nationality"][index] = code_list[index]

In [ ]:
wf.CheckFunctions.change_nation_code(df)

In [ ]:
sns.distplot(df["Max Snatch"])

In [ ]:
sns.distplot(df["Max C/J"])

In [ ]:
sns.distplot(df["Total"])

In [ ]:
sns.distplot(df["Body Weight (kg)"])

In [ ]:
sns.lmplot(x="Year", y="Total", data=df, hue="Gender")

In [ ]:
sns.lmplot(x="Year", y="Max Snatch", data=df, hue="Gender")

In [ ]:
sns.lmplot(x="Year", y="Max C/J", data=df, hue="Gender")

In [ ]:
sns.lmplot(x="Year", y="Body Weight (kg)", data=df, hue="Gender")

In [ ]:
# This changes the "%Y-%m-%d %H:%M:%S" string format in the list to datetime format "%Y-%m-%d %H:%M:%S" 
# to be able to use seaborn graphs below.
for i in range(len(workout_data_list)):
    try:
        temp = datetime.strptime(workout_data_list[i][4], "%Y-%m-%d %H:%M:%S")
        temp.strftime("%Y-%m-%d %H:%M:%S")
        workout_data_list[i][4] = temp
    except:
        pass

In [ ]:
workout_data = pd.DataFrame(workout_data_list)
workout_data.head()

In [ ]:
workout_data.columns = "exercise, sets, reps, weight_lbs, datetime, duration_minutes".split(", ")
workout_data.head()

In [ ]:
# A dataframe for total count of workouts for each exercise
workout_count = workout_data[["exercise", "datetime"]]
workout_count.head()

In [ ]:
# Plot for total count of workouts for each exercise
plt.figure(figsize = (12,9))
sns.set_context("paper", font_scale = 2)
graph = sns.swarmplot(
    x="exercise", 
    y="datetime", 
    data=workout_count, 
    palette=colors, 
    order=exercise_names
    )
graph.set_xticklabels(graph.get_xticklabels(), rotation = 30)
graph.yaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.yaxis.set_major_formatter(mdates.DateFormatter("%b %d, %y"))
graph.set(
    title="Workout Count per Exercise", 
    xlabel="Exercise", 
    ylabel="Date"
    )
plt.savefig("Workout Count per Exercise.png")

In [ ]:
# A dataframe for max weight by each exercise. 
exercise_max = workout_data[["exercise", "weight_lbs"]].groupby("exercise").max()
exercise_max["exercise"] = exercise_max.index
exercise_max

In [ ]:
# Plot of max weight for each exercise
plt.figure(figsize = (12,9))
sns.set_context("paper", font_scale = 2)
graph = sns.barplot(
    x="exercise", 
    y="weight_lbs", 
    data=exercise_max, 
    order=exercise_names
    )
graph.set_xticklabels(graph.get_xticklabels(), rotation = 30)
graph.set(
    title="Max Lifts per Exercise", 
    xlabel="Exercise", 
    ylabel="Weight (lbs)", 
    yticks=np.arange(0, 300, 25)
    )
plt.savefig("Max Lifts per Exercise.png")

In [ ]:
# A dataframe for total intensity(total weight lifted) for each exercise
total_intensity = workout_data[["exercise", "weight_lbs"]].groupby("exercise").sum()
total_intensity["exercise"] = total_intensity.index
total_intensity

In [ ]:
# Plot of total intensity for each exercise
plt.figure(figsize = (12,9))
sns.set_context("paper", font_scale = 2)
graph = sns.barplot(
    x="exercise", 
    y="weight_lbs", 
    data=total_intensity, 
    order=exercise_names
    )
graph.set_xticklabels(graph.get_xticklabels(), rotation=30)
graph.set(
    title="Total Intensity", 
    xlabel="Exercise", 
    ylabel="Total Weight Lifted (lbs)", 
    yticks=np.arange(0, 8000, 500)
    )
plt.savefig("Total Intensity.png")

In [ ]:
# A dataframe for total volume for each exercise
total_reps = workout_data["sets"]*workout_data["reps"]
workout_data["total volume"] = total_reps
total_volume = workout_data[["exercise", "total volume"]].groupby("exercise").sum()
total_volume["exercise"] = total_volume.index
total_volume

In [ ]:
# Plot for total volume for each exercise
plt.figure(figsize = (12,9))
sns.set_context("paper", font_scale = 2)
graph = sns.barplot(
    x="exercise", 
    y="total volume", 
    data=total_volume, 
    order=exercise_names
    )
graph.set_xticklabels(graph.get_xticklabels(), rotation = 30)
graph.set(
    title="Total Volume per Exercise", 
    xlabel="Exercise", 
    ylabel="Total Reps", 
    yticks=np.arange(0, 1200, 100)
    )
plt.savefig("Total Volume.png")

In [ ]:
squats_intensity = workout_data[
    ["exercise", "datetime", "weight_lbs"]
    ].loc[
    (workout_data["exercise"] == "BackSquat") | 
    (workout_data["exercise"] == "OverheadSquat") | 
    (workout_data["exercise"] == "FrontSquat")
    ]
squats_intensity.head()

In [ ]:
squats_volume = workout_data[
    ["exercise", "datetime", "total volume"]
    ].loc[
    (workout_data["exercise"] == "BackSquat") | 
    (workout_data["exercise"] == "OverheadSquat") | 
    (workout_data["exercise"] == "FrontSquat")
    ]
squats_volume.head()

In [ ]:
presses_intensity = workout_data[
    ["exercise", "datetime", "weight_lbs"]
    ].loc[(workout_data["exercise"] == "BenchPress") | 
    (workout_data["exercise"] == "ShoulderPress")]
presses_intensity.head()

In [ ]:
presses_volume = workout_data[
    ["exercise", "datetime", "total volume"]
    ].loc[(workout_data["exercise"] == "BenchPress") | 
    (workout_data["exercise"] == "ShoulderPress")
    ]
presses_volume.head()

In [ ]:
oly_lifts_intensity = workout_data[
    ["exercise", "datetime", "weight_lbs"]
    ].loc[
    (workout_data["exercise"] == "Clean&Jerk") | 
    (workout_data["exercise"] == "Snatch")
    ]
oly_lifts_intensity.head()

In [ ]:
oly_lifts_volume = workout_data[
    ["exercise", "datetime", "total volume"]
    ].loc[(workout_data["exercise"] == "Clean&Jerk") | 
    (workout_data["exercise"] == "Snatch")
    ]
oly_lifts_volume.head()

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="weight_lbs", 
    data=squats_intensity, 
    palette=colors[1:4], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(squats_intensity["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Squats Intensity vs. Time", 
    xlabel="Time", 
    ylabel="Weight (lbs)", 
    yticks=np.arange(0, 250, 25)
    )
plt.legend(
    title="Exercise", 
    loc="upper right", 
    labels=squats_intensity["exercise"].unique()
    )
plt.savefig("Squats Intensity.png")

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="total volume", 
    data=squats_volume, 
    palette=colors[1:4], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(squats_volume["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Squats Volume vs. Time", 
    xlabel="Time", 
    ylabel="Total Reps per Session", 
    yticks=np.arange(0, 55, 5)
    )
plt.legend(
    title="Exercise", 
    loc="upper left", 
    labels=squats_volume["exercise"].unique()
    )
plt.savefig("Squats Volume.png")

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="weight_lbs", 
    data=presses_intensity, 
    palette=colors[4:6], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(presses_intensity["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Presses Intensity vs. Time", 
    xlabel="Time", 
    ylabel="Weight (lbs)", 
    yticks=np.arange(0, 200, 25)
    )
plt.legend(
    title="Exercise", 
    loc="upper right", 
    labels=presses_intensity["exercise"].unique()
    )
plt.savefig("Presses Intensity.png")

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="total volume", 
    data=presses_volume, 
    palette=colors[4:6], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(presses_volume["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Presses Volume vs. Time", 
    xlabel="Time", 
    ylabel="Total Reps per Session", 
    yticks=np.arange(0, 55, 5)
    )
plt.legend(
    title="Exercise", 
    loc="upper left", 
    labels=presses_volume["exercise"].unique()
    )
plt.savefig("Presses Volume.png")

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="weight_lbs", 
    data=oly_lifts_intensity, 
    palette=colors[7:9], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(oly_lifts_intensity["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Olympic Lifts Intensity vs. Time", 
    xlabel="Time", 
    ylabel="Weight (lbs)",
    yticks=np.arange(0, 150, 25)
    )
plt.legend(
    title="Exercise", 
    loc="upper right", 
    labels=oly_lifts_intensity["exercise"].unique()
    )
plt.savefig("Olympic Lifts Intensity.png")

In [ ]:
# Plot comparison for intensity for squats.
plt.figure(figsize = (16,9))

sns.set_context("paper", font_scale = 2)
graph = sns.lineplot(
    x="datetime", 
    y="total volume", 
    data=oly_lifts_volume, 
    palette=colors[7:9], 
    hue="exercise", 
    linewidth=3
    )
graph.set_xticklabels(oly_lifts_volume["datetime"].values, rotation = 30)
graph.xaxis.set_major_locator(mdates.WeekdayLocator(interval=5))
graph.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d/%y"))
graph.set(
    title="Olympic Lifts Volume vs. Time", 
    xlabel="Time", 
    ylabel="Total Reps per Session",
    yticks=np.arange(0, 30, 3)
    )
plt.legend(
    title="Exercise", 
    loc="upper right", 
    labels=oly_lifts_volume["exercise"].unique()
    )
plt.savefig("Olympic Lifts Volume.png")

In [ ]:
""" Analytics Below """

In [ ]:
# Shoulder Press Volume to Deadlift Volme Percent Ratio
dl = total_volume.loc["Deadlift"][0]
sp = total_volume.loc["ShoulderPress"][0]

round(sp/dl*100, 2)

In [ ]:
# Deadlift Max to Shoulder Press Max Percent Ratio
dl = exercise_max.loc["Deadlift"][0]
sp = exercise_max.loc["ShoulderPress"][0]

round(dl/sp*100, 2)

In [ ]:
# Squats Total Volume to Presses Total Volume Percent Ratio
sq = squats_volume["total volume"].sum()
pr = presses_volume["total volume"].sum()

round(sq/pr*100, 2)

In [ ]:
# Squts Total Intensity to Presses Total Intensity Percent Ratio
sq = squats_intensity["weight_lbs"].sum()
pr = presses_intensity["weight_lbs"].sum()

round(sq/pr*100, 2)

In [ ]:
# Snatch Total Volume to Clean&Jerk Total Volume Percent Ratio
cj = total_volume.loc["Clean&Jerk"][0]
sn = total_volume.loc["Snatch"][0]

round(sn/cj*100, 2)

In [ ]:
# Snatch Total Intensity to Clean&Jerk Total Intensity Percent Ratio
cj = total_intensity.loc["Clean&Jerk"][0]
sn = total_intensity.loc["Snatch"][0]

round(sn/cj*100, 2)

In [ ]:
# Front Squat Max to Back Squat Max Percent Ratio
fs = exercise_max.loc["FrontSquat"][0]
bs = exercise_max.loc["BackSquat"][0]

round(fs/bs*100, 2)

In [ ]:
# Average duration of workouts out of 111 workouts with non-null data in duration_minutes
len(workout_data["duration_minutes"].loc[workout_data["duration_minutes"] != -1]) # No. workouts with non-null duration

avg_duration = workout_data["duration_minutes"].loc[workout_data["duration_minutes"] != -1].mean()
round(avg_duration, 2)

In [ ]:
# Average number of sets in workouts
avg_sets = workout_data["sets"].mean()
round(avg_sets, 2)

In [ ]:
# Average number of reps in workouts
avg_reps = workout_data["reps"].mean()
round(avg_reps, 2)

In [ ]:
# Average weight lifted in workouts
avg_weight = workout_data["weight_lbs"].mean()
round(avg_weight, 2)